# Usa una imagen oficial de PHP con Apache
FROM php:8.1-apache

# Copia el contenido de la carpeta 'html' a /var/www/html en el contenedor
COPY html/ /var/www/html/

# Habilita mod_rewrite (si lo necesitas)
RUN a2enmod rewrite

# Configura Apache para que use 1_index_del_home.html como el archivo predeterminado
RUN echo "DirectoryIndex 1_index_del_home.html" >> /etc/apache2/apache2.conf

# Expone el puerto 80
EXPOSE 80
